#!/bin/sh

GITDIRECTORY=`cat $HOME/.git_directory_name`

cd "$HOME/$GITDIRECTORY"
echo ""
echo -e "\033[0;34m[Run branch]\033[0;39m"
git branch | grep '*' | awk '{print $2;}'
echo ""
echo -e "\033[0;34m[Git_Status]\033[0;39m"
GITSTATUS=`git status -s | wc -l`
if [ $GITSTATUS = 0 ]; then
	echo " File None"
else
	echo ""
	echo "[ Update Files List ]"
	git status -s
fi
echo ""
