#!/bin/sh

GITDIRECTORY=`cat ~/.git_directory_name`

cd "$HOME/$GITDIRECTORY"
echo ""
echo -e "\033[0;34m[Work branch]\033[0;39m"
git branch | grep '*' | awk '{print $2;}'
echo ""
echo -e "\033[0;34m[Local branch list]\033[0;39m"
git branch -a | grep -v '*' | grep -v "remotes" | awk '{print $1;}'
echo ""
echo -e "\033[0;34m[Remote branch list]\033[0;39m"
git branch -a | grep -v '*' | grep "remotes" | awk '{print $1;}'
echo ""
