#!/bin/sh
GITDIRECTORY=`cat $HOME/.git_directory_name`

cd "$HOME/$GITDIRECTORY"
GITDEVELOPCHK=`git branch | grep develop | wc -l`

GITSTATUS=`git status | grep -v 'nothing to commit, working directory clean' | grep -v '#' | wc -l`
if [ "$GITSTATUS" != 0 ]; then
        echo "not branch change"
        exit 1
fi

if [ "$GITDEVELOPCHK" != 0 ]; then
	git checkout develop
	echo -e "\033[0;34m[Branch Update]\033[0;39m"
	git pull
fi




